### PR TITLE
add more testing

### LINKED ISSUE #25: Improve testing
It would be nice to add more testing to validate the build.

### PR DESCRIPTION
**Pull request by mikemhenry**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Fixes #25

### CODE REVIEW

**Comment by mikemhenry** [comment]
Might have to skip the tests on platforms that doesn't work, but this worked for me locally on linux x86

**Comment by mikemhenry** [comment]
julia does not exist on the ppc64le platform so need to skip it (or get a julia build on that platform)

**Comment by mattwthompson** [comment]
I'd quite strongly prefer skipping that platform

**Comment by mikemhenry** [comment]
@mattwthompson :100: agree

**Review by mattwthompson — APPROVED** [review]
LGTM % the last runs finishing successfully

I'm quite surprised this worked fairly cleanly with a modest amount of work, and also that the tests run so quickly. I think we have feedstocks that take this as long to get _to_ the building stage as this one does to finish

**Comment by mikemhenry** [comment]
ditto! I thik sometimes python gest a little I/O bound since 5m is really fast for a linux build on conda-forge IMHO.

I also don't think this patch is nessacary to upstream since it just modofies the testing script to use the packmol in the `PATH` instead of one at a hard-coded location, but for how upstream does their testing, that seems like a fine way to do it.

**Pull request merged**
